[project]
name = "agentic-counter-surveillance"
version = "0.1.0"
description = "A software based on agentic architecture"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.7",
]
